#!/bin/sh
# Set the global colorscheme (requieres wptk https://github.com/deviantfero/wpgtk)
wpg -R wallpaper.png 
wpg -s wallpaper.png
source "${HOME}/rice_assets/colors.sh" 

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm" 

# Setting up workspaces

# General bspwm config options
bspc config border_width				0 #was 5
bspc config window_gap					0 #was 20
#bspc config border_radius				 2
bspc config focus_follows_pointer       true
#bspc config gapless_monocle             true
bspc config pointer_follows_focus       true
#bspc config single_monocle              true
bspc config top_monocle_padding         20
bspc config left_monocle_padding        20 
bspc config right_monocle_padding       20 
bspc config bottom_monocle_padding      20 
#bspc config ignore_ewmh_fullscreen      enter
bspc config ignore_ewmh_struts          true 
#bspc config top_padding                 40 #40
# dual screens shananigans
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true


# Colors
bspc config focused_border_color            "$color9"
bspc config active_border_color             "$color9"
bspc config normal_border_color             "$color1"
bspc config urgent_border_color             "$color1"
bspc config presel_feedback_color           "$color1"
bspc config focused_locked_border_color     "$color1"
bspc config active_locked_border_color      "$color1"
bspc config normal_locked_border_color      "$color1"
bspc config focused_sticky_border_color     "$color1"
bspc config active_sticky_border_color      "$color1"
bspc config normal_sticky_border_color      "$color1"
bspc config focused_private_border_color    "$color1"
bspc config active_private_border_color     "$color1"
bspc config normal_private_border_color     "$color1"

"$BSPWM_CONFIG/screens" &
"$BSPWM_CONFIG/autostart" &